# Generated by Django 6.0.2 on 2026-03-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('sha256_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='Size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
