# Generated by Django 6.0.2 on 2026-03-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hashtool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileregistry',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
