# Generated by Django 6.0.2 on 2026-03-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hashtool', '0003_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileregistry',
            options={'permissions': [('can_archive', 'Can trigger the archival process')]},
        ),
    ]
