# Generated by Django 6.0.2 on 2026-03-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hashtool', '0004_alter_fileregistry_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
